advertising_board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from main.sitemaps import MainSitemap


sitemaps = {'main': MainSitemap}

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # user management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('subscription/', include('subscription.urls', namespace='subscription')),

    # the sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertising_board/main/urls.py
from django.urls import path

from .views import (HomeView, ListAdView,
                    AdCreateView, AdUpdateView,
                    AdDetailView, RobotsTXTView)


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='home_url'),
    path('ads/', ListAdView.as_view(), name='list_ad_url'),
    path('ads/add', AdCreateView.as_view(), name='create_ad_url'),
    path('ads/<int:ad_id>/edit/', AdUpdateView.as_view(), name='update_ad_url'),
    path('ad/<int:ad_id>/', AdDetailView.as_view(), name='detail_ad_url'),
    path('robots.txt', RobotsTXTView.as_view())
]

advertising_board/main/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from sorl.thumbnail import ImageField, delete

from accounts.models import Seller


class BaseModel(models.Model):
    """ Base model class.

    :param title: Ad title
    :type models: class: models.CharField
    """
    title = models.CharField(max_length=100, verbose_name='Заголовок')

    class Meta:
        abstract = True


class Category(BaseModel):
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Slug')

    class Meta:
        ordering = ('-title',)
        verbose_name = 'Категория(ю)'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.title}'


class Tag(BaseModel):
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Slug')

    class Meta:
        ordering = ('-title',)
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return f'Тэг: {self.title}'


class AdType(models.IntegerChoices):
    archived = 0, 'АРХИВИРОВАННОЕ'
    not_archived = 1, 'НЕАРХИВИРОВАННОЕ'


class AdCustomManager(models.Manager):
    def get_page_objects(self, page_number, slug_tag=None):
        queryset = []
        if slug_tag:
            tag = get_object_or_404(Tag, slug=slug_tag)
            queryset = self.get_by_tag(tag)
        else:
            queryset = self.all()
        pagintator = Paginator(queryset, 10)
        page_ads = pagintator.get_page(page_number)
        return page_ads

    def get_by_tag(self, tag):
        return self.filter(tags__slug=tag.slug)

    def create_or_update_ad(self, image_formset, ad_form):
        ad = ad_form.save()
        image_formset.instance = ad
        image_formset.save()
        return ad

    def search_ads(self, message):
        result = set()
        ads = []
        if message:
            ads_by_title = list(self.filter(title__icontains=message))
            ads_by_description = list(self.filter(description__icontains=message))
            result.update(set(ads_by_title), set(ads_by_description))
            if result:
                ads = [{'title': ad.title, 'url': ad.get_absolute_url()} for ad in result]
        return ads


class Ad(BaseModel):
    description = models.TextField(blank=True, verbose_name='Описание')
    category = models.ForeignKey(Category, related_name='ads', on_delete=models.CASCADE, verbose_name='Категория')
    seller = models.ForeignKey(Seller, related_name='ads', on_delete=models.CASCADE, verbose_name='Продавец')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    tags = models.ManyToManyField(Tag, related_name='ads', verbose_name='Тэги')
    price = models.PositiveIntegerField(default=0, verbose_name='Цена')
    type_ad = models.IntegerField(choices=AdType.choices, default=AdType.not_archived, verbose_name='Тип  объявления')

    objects = AdCustomManager()

    class Meta:
        ordering = ('-created_at',)
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"

    def __str__(self):
        return f'Объявление: {self.title}; Категория: {self.category}'

    def get_absolute_url(self):
        return reverse("main:detail_ad_url", kwargs={"ad_id": self.pk})


class ArchivedAdsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type_ad=AdType.archived)


class ArchiveAds(Ad):
    objects = ArchivedAdsManager()

    class Meta:
        proxy = True
        verbose_name = "Архивное объявление"
        verbose_name_plural = "Архивные объявления"


class Picture(models.Model):
    img = ImageField(upload_to="ads/%Y/%m/%d/", verbose_name='Фото')
    ad = models.ForeignKey(Ad, related_name='imgs', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"

    def _remove_on_update_image(self):
        try:
            old_img = Picture.objects.get(id=self.id)
        except Picture.DoesNotExist:
            return
        if self.img and old_img.img and self.img != old_img:
            delete(old_img.img.path)

    def save(self, *args, **kwargs):
        self._remove_on_update_image()
        return super().save(*args, **kwargs)

advertising_board/main/forms.py
from django.forms import (inlineformset_factory, BaseInlineFormSet,
                          ModelForm)
from sorl.thumbnail import delete

from .models import Ad, Picture


class AdForm(ModelForm):

    class Meta:
        model = Ad
        fields = ('seller', 'title', 'description',
                  'category', 'tags', 'price', 'type_ad')


class BaseImageFormset(BaseInlineFormSet):

    def save(self, commit=True):
        self._delete_image_file()
        return super().save(commit=commit)

    def _delete_image_file(self):
        for form in self.forms:
            data = form.cleaned_data
            if data.get('DELETE'):
                try:
                    img_path = data.get('id').img.path
                    delete(img_path)
                except AttributeError:
                    pass


ImageFormset = inlineformset_factory(parent_model=Ad, model=Picture,
                                     extra=4, fields=('img',),
                                     formset=BaseImageFormset)

advertising_board/main/views.py
import socket

from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.http import HttpResponse

from .models import Ad
from .forms import AdForm
from .mixins import CheckOwnerAdMixin, AdCreateUpdateMixin


class HomeView(View):
    template_name = 'main/index.html'

    def get(self, request, *args, **kwargs):
        id = socket.gethostname
        return render(request, self.template_name, context={'id': id})


class ListAdView(ListView):
    model = Ad
    template_name = 'main/ad_list.html'
    context_object_name = 'page_obj'

    def get_queryset(self):
        slug_tag = self.request.GET.get('tag')
        page_number = self.request.GET.get('page')
        page_ads = Ad.objects.get_page_objects(page_number=page_number, slug_tag=slug_tag)
        return page_ads


class AdDetailView(DetailView):
    model = Ad
    template_name = 'main/ad_detail.html'
    context_object_name = 'ad'
    pk_url_kwarg = 'ad_id'

    def get_object(self, queryset=None):
        ad_id = self.kwargs.get('ad_id')
        key = f"ad_id={ad_id}"
        ad = cache.get(key)
        if not ad:
            ad = get_object_or_404(Ad, pk=ad_id)
            cache.set(key, ad)
        return ad


class AdCreateView(LoginRequiredMixin, PermissionRequiredMixin,
                   AdCreateUpdateMixin, CreateView):
    model = Ad
    form_class = AdForm
    template_name = 'main/update_create_ad.html'
    succes_message = 'Объявление успешно создано.'
    login_url = '/accounts/login/'
    permission_required = ('main.add_ad', )
    permission_denied_message = "You don't have permission to add ad."

    def post(self, request, *args, **kwargs):
        self.object = None
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creation'] = True
        return context


class AdUpdateView(LoginRequiredMixin, CheckOwnerAdMixin,
                   AdCreateUpdateMixin, UpdateView):
    model = Ad
    form_class = AdForm
    template_name = 'main/update_create_ad.html'
    pk_url_kwarg = 'ad_id'
    succes_message = 'Объявление успешно обновлено.'
    login_url = '/accounts/login/'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class RobotsTXTView(View):
    http_method_names = ['get']

    def get(self, request):
        lines = [
            "User-Agent: *",
            "Disallow: /seller/",
            "Disallow: /seller/confirm-phone-number/",
        ]
        return HttpResponse("\n".join(lines), content_type="text/plain")

advertising_board/main/templates/main/ad_detail.html
{% extends 'base.html' %}

{% load thumbnail %}


{% block title %}{{ ad.title }}{% endblock title %}

{% block content %}
  <h1 class="h3 text-center my-4">{{ ad.title }}</h1>
  <div class="row">
    {% for item in ad.imgs.all %}
      <div class="col-md-auto thumb">
        <a data-fancybox="gallery" href="{{ item.img.url }}">
          {% thumbnail item.img "100x100" crop="center" quality=90 as img %}
            <img src="{{ img.url }}">
          {% endthumbnail %}
        </a>
      </div>
    {% endfor %}
  </div>
  <div class="card">
  <div class="card-body">
    <h5 class="card-title">Заголовок объявления: {{ ad.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Категория: {{ ad.category.title }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Продавец: {{ ad.seller.seller }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Тэги: {% for tag in ad.tags.all %}<span>{{ tag.title }}, </span>{% endfor %}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Электронная почта продавца: {{ ad.seller.seller.email }}</h6>
    <p class="card-text">{{ ad.description }}</p>
    {% if user.is_authenticated %}
      {% if user.seller.id == ad.seller.id %}
      <a href="{% url 'main:update_ad_url' ad_id=ad.id %}" class="card-link">Редактировать объявление</a>
      {% endif %}
    {% endif %}
    </div>
</div>

{% endblock content %}

advertising_board/main/templates/main/ad_list.html
{% extends 'base.html' %}
{% load sidebar %}
{% load static %}

{% block title %}Все объявления{% endblock title %}

{% block content %}

  <div class="row">
    <div class="col justify-content-md-center">
      <table class="table table-dark" style:>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Заголовок объявления</th>
            <th scope="col">Продавец</th>
          </tr>
        </thead>
        <tbody>
          {% for ad in page_obj %}
          <tr>
            <th scope="row">{{ ad.id }}</th>
            <td><a href="{{ ad.get_absolute_url }}">{{ ad.title }}</a></td>
            <th scope="row">{{ ad.seller.seller }}</th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-auto">
      {% show_tags %}
    </div>
  </div>
  {% include 'includes/_pagination.html'%}
{% endblock content %}

advertising_board/main/templates/main/index.html
{% extends 'base.html' %}


{% block title %}Avertising Board: недвижимость, транспорт, работа, услуги, вещи{% endblock title %}

{% block content %}
<div class="bg-light p-5 rounded">
  <h1>Home page</h1>
  <p>{{ id }}</p>
</div>
{% endblock content %}

advertising_board/main/templates/main/tags.html
{% load cache %}
<h2>Tags</h2>
{% cache 600 tags %}
{% for tag in tags %}
  <p><a href="?tag={{ tag.slug }}">{{ tag.title }}</a></p>
{% endfor %}
{% endcache %}

advertising_board/main/templates/main/update_create_ad.html
{% extends 'base.html' %}
{% load addclass %}

{% block title %}Создание объявления{% endblock title %}

{% block content %}
  <div class="mt-3">{% if creation %}<h2>Новое объявление</h2>{% else %}<h2>Редактирование объявления</h2>{% endif %}</div>
  <hr>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ image_formset.management_form }}
    {% for field in form %}
      <div class="form-group mb-3">
          {{ field.label_tag }} {{ field|addclass:'form-control mb-3' }}
          {{ field.errors }}
      </div>
    {% endfor %}
    <p>Фото:</p>
    {% for form in image_formset %}
      {{ form.id }}
      <div class="form-control">
        {{ form.img|addclass:'form-control-file' }} <span>{{ form.DELETE }} {{ form.DELETE.label  }}</span>
        {{ form.img.errors }}
      </div>
    {% endfor %}
    <input class="btn btn-primary mb-2" type="submit"
      value="{% if creation %}Создать объявление{% else %}Обновить объявление{% endif %}">
  </form>
{% endblock content %}