advertising_board/accounts/urls.py
from django.urls import path

from .views import SellerConfirmPhoneNumberView, SellerUpdateView

app_name = 'accounts'
urlpatterns = [

    # profile
    path('seller/', SellerUpdateView.as_view(), name='seller_url'),
    path('seller/confirm-phone-number/', SellerConfirmPhoneNumberView.as_view(), name='confirm_phone_number_url')

]

advertising_board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from main.sitemaps import MainSitemap


sitemaps = {'main': MainSitemap}

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # user management
    path('accounts/', include('allauth.urls')),

    # Local apps
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('subscription/', include('subscription.urls', namespace='subscription')),

    # the sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertising_board/main/urls.py
from django.urls import path

from .views import (HomeView, ListAdView,
                    AdCreateView, AdUpdateView,
                    AdDetailView, RobotsTXTView)


app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='home_url'),
    path('ads/', ListAdView.as_view(), name='list_ad_url'),
    path('ads/add', AdCreateView.as_view(), name='create_ad_url'),
    path('ads/<int:ad_id>/edit/', AdUpdateView.as_view(), name='update_ad_url'),
    path('ad/<int:ad_id>/', AdDetailView.as_view(), name='detail_ad_url'),
    path('robots.txt', RobotsTXTView.as_view())
]

advertising_board/subscription/urls.py
from django.urls import path

from .views import SubscribeView


app_name = 'subscription'

urlpatterns = [
    path('subscribe/', SubscribeView.as_view(), name='subscribe_url'),
    # path('unsubscribe/', UnsubscribeView.as_view(), name='unsubscribe_url'),
]

advertising_board/main/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from sorl.thumbnail import ImageField, delete

from accounts.models import Seller


class BaseModel(models.Model):
    """ Base model class.

    :param title: Ad title
    :type models: class: models.CharField
    """
    title = models.CharField(max_length=100, verbose_name='Заголовок')

    class Meta:
        abstract = True


class Category(BaseModel):
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Slug')

    class Meta:
        ordering = ('-title',)
        verbose_name = 'Категория(ю)'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return f'{self.title}'


class Tag(BaseModel):
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Slug')

    class Meta:
        ordering = ('-title',)
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return f'Тэг: {self.title}'


class AdType(models.IntegerChoices):
    archived = 0, 'АРХИВИРОВАННОЕ'
    not_archived = 1, 'НЕАРХИВИРОВАННОЕ'


class AdCustomManager(models.Manager):
    def get_page_objects(self, page_number, slug_tag=None):
        queryset = []
        if slug_tag:
            tag = get_object_or_404(Tag, slug=slug_tag)
            queryset = self.get_by_tag(tag)
        else:
            queryset = self.all()
        pagintator = Paginator(queryset, 10)
        page_ads = pagintator.get_page(page_number)
        return page_ads

    def get_by_tag(self, tag):
        return self.filter(tags__slug=tag.slug)

    def create_or_update_ad(self, image_formset, ad_form):
        ad = ad_form.save()
        image_formset.instance = ad
        image_formset.save()
        return ad

    def search_ads(self, message):
        result = set()
        ads = []
        if message:
            ads_by_title = list(self.filter(title__icontains=message))
            ads_by_description = list(self.filter(description__icontains=message))
            result.update(set(ads_by_title), set(ads_by_description))
            if result:
                ads = [{'title': ad.title, 'url': ad.get_absolute_url()} for ad in result]
        return ads


class Ad(BaseModel):
    description = models.TextField(blank=True, verbose_name='Описание')
    category = models.ForeignKey(Category, related_name='ads', on_delete=models.CASCADE, verbose_name='Категория')
    seller = models.ForeignKey(Seller, related_name='ads', on_delete=models.CASCADE, verbose_name='Продавец')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    tags = models.ManyToManyField(Tag, related_name='ads', verbose_name='Тэги')
    price = models.PositiveIntegerField(default=0, verbose_name='Цена')
    type_ad = models.IntegerField(choices=AdType.choices, default=AdType.not_archived, verbose_name='Тип  объявления')

    objects = AdCustomManager()

    class Meta:
        ordering = ('-created_at',)
        verbose_name = "Объявление"
        verbose_name_plural = "Объявления"

    def __str__(self):
        return f'Объявление: {self.title}; Категория: {self.category}'

    def get_absolute_url(self):
        return reverse("main:detail_ad_url", kwargs={"ad_id": self.pk})


class ArchivedAdsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type_ad=AdType.archived)


class ArchiveAds(Ad):
    objects = ArchivedAdsManager()

    class Meta:
        proxy = True
        verbose_name = "Архивное объявление"
        verbose_name_plural = "Архивные объявления"


class Picture(models.Model):
    img = ImageField(upload_to="ads/%Y/%m/%d/", verbose_name='Фото')
    ad = models.ForeignKey(Ad, related_name='imgs', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"

    def _remove_on_update_image(self):
        try:
            old_img = Picture.objects.get(id=self.id)
        except Picture.DoesNotExist:
            return
        if self.img and old_img.img and self.img != old_img:
            delete(old_img.img.path)

    def save(self, *args, **kwargs):
        self._remove_on_update_image()
        return super().save(*args, **kwargs)

advertising_board/templates/includes/_footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">© {% now 'Y' %} Advertising.</span>
  </div>
</footer>

advertising_board/templates/includes/_header.html
{% load flatpages %}
{% load custom_tags %}
{% load custom_filters %}
{% load thumbnail %}

<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="">{{ 'Привет, мир!'|reverse_string }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:home_url' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:list_ad_url' %}">Ads</a>
          </li>
          {% if user.is_authenticated and perms.main.add_ad %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:create_ad_url' %}">Создать объявление</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'subscription:subscribe_url' %}">Подписаться на рассылку</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          {% get_flatpages as flatpages %}
          {% for page in flatpages %}
            <li class="nav-item">
              <a class="nav-link" href="{{ page.url }}">{{ page.title  }}</a>
            </li>
          {% endfor %}
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a href="{% url 'account_logout' %}" class="nav-link text-white">
              <i class="fas fa-user"></i> Log Out
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class="nav-link text-white">
              <i class="fas fa-user"></i> Log In
            </a>
            {% endif %}
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success btn-space" type="submit">Search</button>
        </form>
        <button type="button" class="btn btn-primary btn-space">Notifications <span class="badge">{% notifications %}</span></button>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'accounts:seller_url' %}" class="nav-link text-white">
              <i class="fas fa-user"></i> {{ user.username }}
            </a>
          </li>
          <li>
            {% thumbnail user.seller.img "50x50" crop="center" quality=90 as img %}
            <a href="{% url 'accounts:seller_url' %}"><img src="{{ img.url }}"></a>
            {% endthumbnail %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

advertising_board/templates/includes/_messages.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class="shadow-custom messages alert alert-danger col-lg-4 mx-auto text-center">
        {{ message }}
        <a href="" class="close">x</a>
      </div>
    {% else %}
      <div class="shadow-custom messages alert alert-{{ message.tags }} col-lg-4 mx-auto text-center">
        {{ message }}
        <a href="" class="close">x</a>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

advertising_board/templates/includes/_pagination.html
{% load url_encode %}

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% url_encode page=page_obj.previous_page_number %}">Previous</a></li>
    {% endif %}

    {% for p in page_obj.paginator.page_range %}
      {% if page_obj.number == p %}
      <li class="page-item active" aria-current="page">
        <span class="page-link">{{ p }}</span>
      </li>
      {% elif page_obj.number|add:-5 < p and p < page_obj.number|add:5 %}
        <li class="page-item"><a class="page-link" href="?{% url_encode page=p %}">{{ p }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?{% url_encode page=page_obj.next_page_number %}">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

advertising_board/templates/includes/_technical_work.html
<div class="container">
  <h2>На сайте проводятся технические работы. Но уже скоро мы снова будем с Вами. Не грустите.</h2>
  <img src="https://zap-pro.ru/upload/news/30.png" alt="">
</div>